import { execFile } from "child_process";
import { accessSync, constants, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { delimiter, join } from "path";

const MINIMUM_TMUX_VERSION = { major: 3, minor: 2 } as const;
const MAX_SOCKET_PATH_BYTES = 100;
const COMMAND_TIMEOUT_MS = 5_000;

/**
 * What a managed pane reports as its title.
 *
 * Not `#{pane_title}`: tmux seeds that from `gethostname()` and only ever
 * changes it if the program inside emits an OSC 0/2 title, which shells do not
 * do once `$TMUX` is set — prompt frameworks suppress it precisely because tmux
 * is supposed to own the title. Every managed tab therefore ends up named after
 * the machine.
 *
 * So derive it instead: the current directory while the pane sits at a prompt,
 * the running command otherwise. The `m:` test asks whether
 * `pane_current_command` is the basename of `default-shell` — `#{b:...}` cannot
 * be used here because the `b:` modifier does not apply to a nested expansion
 * (`#{b:#{default-shell}}` yields `/bin/zsh`, unchanged). The slash in the
 * pattern is load-bearing: matching on a bare wildcard would also match the
 * command `sh` against `/bin/zsh` and hide a real `sh` invocation.
 */
const MANAGED_TMUX_TITLE_FORMAT =
  "#{?#{m:*/#{pane_current_command},#{default-shell}},#{b:pane_current_path},#{pane_current_command}}";

const MANAGED_TMUX_CONFIG = `# Generated by Devspace. User tmux configuration is intentionally not loaded.
set -g status off
set -g mouse on
set -g history-limit 10000
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB:clipboard"
set -as terminal-features ",xterm-256color:RGB:clipboard"
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
set -g extended-keys on
set -g escape-time 10
set -g aggressive-resize on
set -g destroy-unattached off
set -g exit-unattached off
set -g set-titles on
set -g set-titles-string "${MANAGED_TMUX_TITLE_FORMAT}"
`;

/**
 * Options re-pushed to a server that is already running.
 *
 * tmux reads `-f <conf>` only when it *starts* the server. Managed sessions are
 * deliberately allowed to outlive the app, so a server started by an older
 * release keeps that release's options forever — including a title format that
 * has since been fixed. These are the ones worth healing in place; everything
 * else in the config is either inert for a live server or too invasive to
 * change under a running session.
 */
const MANAGED_TMUX_RUNTIME_OPTIONS: ReadonlyArray<readonly [string, string]> = [
  ["set-titles", "on"],
  ["set-titles-string", MANAGED_TMUX_TITLE_FORMAT],
];

export type TmuxCommandResult = {
  exitCode: number;
  stdout: string;
  stderr: string;
};

export type TmuxCommandRunner = (
  binaryPath: string,
  args: string[],
  env: NodeJS.ProcessEnv,
) => Promise<TmuxCommandResult>;

type ManagedTmuxOptions = {
  userDataPath: string;
  resourcesPath: string;
  isPackaged: boolean;
  env?: NodeJS.ProcessEnv;
  binaryPath?: string;
  runCommand?: TmuxCommandRunner;
};

type EnsureManagedSessionOptions = {
  sessionId: string;
  cwd?: string;
  envVars?: Record<string, string>;
};

export type ManagedTmuxSession = {
  sessionId: string;
  attachedClients: number;
  createdAt: number;
};

function isExecutable(filePath: string): boolean {
  try {
    accessSync(filePath, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function findOnPath(command: string, pathValue: string | undefined): string | null {
  if (!pathValue) return null;
  for (const directory of pathValue.split(delimiter)) {
    if (!directory) continue;
    const candidate = join(directory, command);
    if (isExecutable(candidate)) return candidate;
  }
  return null;
}

export function resolveManagedTmuxBinary(options: {
  resourcesPath: string;
  isPackaged: boolean;
  env?: NodeJS.ProcessEnv;
}): string | null {
  const env = options.env ?? process.env;
  const bundledPath = join(options.resourcesPath, "bin", "tmux");

  if (isExecutable(bundledPath)) return bundledPath;
  if (options.isPackaged) return null;

  const explicitPath = env.DEVSPACE_TMUX_PATH?.trim();
  if (explicitPath && isExecutable(explicitPath)) return explicitPath;

  return findOnPath("tmux", env.PATH);
}

export function resolveExternalTmuxBinary(env: NodeJS.ProcessEnv = process.env): string | null {
  const explicitPath = env.DEVSPACE_EXTERNAL_TMUX_PATH?.trim();
  if (explicitPath && isExecutable(explicitPath)) return explicitPath;
  return findOnPath("tmux", env.PATH);
}

function cleanTmuxEnvironment(
  baseEnv: NodeJS.ProcessEnv,
  additions?: Record<string, string>,
): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...baseEnv, ...additions };
  delete env.TMUX;
  delete env.TMUX_PANE;
  return env;
}

function parseTmuxVersion(output: string): { major: number; minor: number } | null {
  const match = output.trim().match(/^(?:tmux\s+)?(\d+)\.(\d+)/);
  if (!match) return null;
  return { major: Number(match[1]), minor: Number(match[2]) };
}

function isSupportedVersion(version: { major: number; minor: number }): boolean {
  return (
    version.major > MINIMUM_TMUX_VERSION.major ||
    (version.major === MINIMUM_TMUX_VERSION.major && version.minor >= MINIMUM_TMUX_VERSION.minor)
  );
}

function versionsMatch(
  left: { major: number; minor: number },
  right: { major: number; minor: number },
): boolean {
  return left.major === right.major && left.minor === right.minor;
}

function reportsNoRunningServer(result: TmuxCommandResult): boolean {
  const detail = `${result.stdout}\n${result.stderr}`;
  return /no server running|connection refused|error connecting to .*managed\.sock/i.test(detail);
}

function assertManagedSessionId(sessionId: string): void {
  if (!/^[A-Za-z0-9_-]{1,128}$/.test(sessionId)) {
    throw new Error("Invalid managed terminal session ID");
  }
}

function sessionNameForId(sessionId: string): string {
  assertManagedSessionId(sessionId);
  return `devspace-${sessionId}`;
}

export function quoteCommandArgument(value: string): string {
  if (value.includes("\0")) {
    throw new Error("Command arguments cannot contain NUL bytes");
  }
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

const defaultRunCommand: TmuxCommandRunner = (binaryPath, args, env) =>
  new Promise((resolve) => {
    execFile(
      binaryPath,
      args,
      {
        env,
        encoding: "utf8",
        timeout: COMMAND_TIMEOUT_MS,
        maxBuffer: 1024 * 1024,
      },
      (error, stdout, stderr) => {
        const exitCode =
          error && typeof (error as NodeJS.ErrnoException & { code?: unknown }).code === "number"
            ? ((error as NodeJS.ErrnoException & { code: number }).code ?? 1)
            : error
              ? 1
              : 0;
        resolve({ exitCode, stdout, stderr });
      },
    );
  });

export class ManagedTmuxManager {
  readonly socketPath: string;
  readonly configPath: string;

  private readonly env: NodeJS.ProcessEnv;
  private readonly runCommand: TmuxCommandRunner;
  private readonly configuredBinaryPath: string | undefined;
  private binaryPath: string | null | undefined;
  private versionChecked = false;
  private pendingReady: Promise<void> | null = null;
  private readonly pendingSessions = new Map<string, Promise<void>>();

  constructor(private readonly options: ManagedTmuxOptions) {
    const tmuxDirectory = join(options.userDataPath, "tmux");
    this.socketPath = join(tmuxDirectory, "managed.sock");
    this.configPath = join(tmuxDirectory, "tmux.conf");
    this.env = options.env ?? process.env;
    this.runCommand = options.runCommand ?? defaultRunCommand;
    this.configuredBinaryPath = options.binaryPath;
  }

  getBinaryPath(): string | null {
    if (this.binaryPath !== undefined) return this.binaryPath;

    if (this.configuredBinaryPath) {
      this.binaryPath = this.configuredBinaryPath;
      return this.binaryPath;
    }

    this.binaryPath = resolveManagedTmuxBinary({
      resourcesPath: this.options.resourcesPath,
      isPackaged: this.options.isPackaged,
      env: this.env,
    });
    return this.binaryPath;
  }

  isAvailable(): boolean {
    return this.getBinaryPath() !== null;
  }

  async ensureSession(options: EnsureManagedSessionOptions): Promise<void> {
    assertManagedSessionId(options.sessionId);
    const existing = this.pendingSessions.get(options.sessionId);
    if (existing) return existing;

    const pending = this.ensureSessionOnce(options).finally(() => {
      this.pendingSessions.delete(options.sessionId);
    });
    this.pendingSessions.set(options.sessionId, pending);
    return pending;
  }

  async hasSession(sessionId: string): Promise<boolean> {
    await this.ensureReady();
    const result = await this.run(["has-session", "-t", sessionNameForId(sessionId)]);
    if (result.exitCode === 0) return true;
    if (result.exitCode === 1) return false;
    throw new Error(result.stderr.trim() || "Unable to inspect managed terminal session");
  }

  buildAttachCommand(sessionId: string): string {
    const binaryPath = this.requireBinaryPath();
    const sessionName = sessionNameForId(sessionId);
    return [
      "/usr/bin/env",
      "-u",
      "TMUX",
      "-u",
      "TMUX_PANE",
      "TERM=xterm-256color",
      binaryPath,
      "-S",
      this.socketPath,
      "-f",
      this.configPath,
      "attach-session",
      "-t",
      sessionName,
    ]
      .map(quoteCommandArgument)
      .join(" ");
  }

  async killSession(sessionId: string): Promise<boolean> {
    if (!(await this.hasSession(sessionId))) return false;
    const result = await this.run(["kill-session", "-t", sessionNameForId(sessionId)]);
    if (result.exitCode !== 0) {
      throw new Error(result.stderr.trim() || "Unable to kill managed terminal session");
    }
    return true;
  }

  async listSessions(): Promise<ManagedTmuxSession[]> {
    await this.ensureReady();
    const result = await this.run([
      "list-sessions",
      "-F",
      "#{session_name}\t#{session_attached}\t#{session_created}",
    ]);
    if (result.exitCode === 1) return [];
    if (result.exitCode !== 0) {
      throw new Error(result.stderr.trim() || "Unable to list managed terminal sessions");
    }

    return result.stdout
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean)
      .flatMap((line) => {
        const [name, attached, created] = line.split("\t");
        if (!name?.startsWith("devspace-")) return [];
        const sessionId = name.slice("devspace-".length);
        if (!/^[A-Za-z0-9_-]{1,128}$/.test(sessionId)) return [];
        return [
          {
            sessionId,
            attachedClients: Number.parseInt(attached ?? "0", 10) || 0,
            createdAt: Number.parseInt(created ?? "0", 10) || 0,
          },
        ];
      });
  }

  private async ensureSessionOnce(options: EnsureManagedSessionOptions): Promise<void> {
    await this.ensureReady();
    if (await this.hasSession(options.sessionId)) return;

    const args = ["new-session", "-d", "-s", sessionNameForId(options.sessionId)];
    if (options.cwd) args.push("-c", options.cwd);
    for (const [key, value] of Object.entries(options.envVars ?? {})) {
      args.push("-e", `${key}=${value}`);
    }

    const result = await this.run(args, options.envVars);
    if (result.exitCode === 0) return;

    // Two renderer requests can race across process boundaries. Treat an
    // already-created session as success, but never restart the server.
    if (await this.hasSession(options.sessionId)) return;
    throw new Error(result.stderr.trim() || "Unable to create managed terminal session");
  }

  private async ensureReady(): Promise<void> {
    const socketBytes = Buffer.byteLength(this.socketPath, "utf8");
    if (socketBytes > MAX_SOCKET_PATH_BYTES) {
      throw new Error(`Managed tmux socket path is too long (${socketBytes} bytes)`);
    }
    if (this.versionChecked) return;

    // `versionChecked` is only set at the very end, after two awaited tmux
    // invocations. Restoring a workspace calls this once per managed pane, all
    // in the same tick, so without sharing the in-flight run every caller would
    // rewrite the config file and spawn its own version probes before the first
    // one finished. Same shape as pendingSessions: cleared on settle, so a
    // failure is retried rather than cached.
    const existing = this.pendingReady;
    if (existing) return existing;

    const pending = this.ensureReadyOnce().finally(() => {
      this.pendingReady = null;
    });
    this.pendingReady = pending;
    return pending;
  }

  private async ensureReadyOnce(): Promise<void> {
    mkdirSync(join(this.options.userDataPath, "tmux"), { recursive: true, mode: 0o700 });
    let currentConfig: string | null = null;
    try {
      currentConfig = readFileSync(this.configPath, "utf8");
    } catch {
      // First launch.
    }
    if (currentConfig !== MANAGED_TMUX_CONFIG) {
      writeFileSync(this.configPath, MANAGED_TMUX_CONFIG, { encoding: "utf8", mode: 0o600 });
    }

    const versionResult = await this.runCommand(
      this.requireBinaryPath(),
      ["-V"],
      cleanTmuxEnvironment(this.env),
    );
    const version = parseTmuxVersion(versionResult.stdout);
    if (versionResult.exitCode !== 0 || !version || !isSupportedVersion(version)) {
      throw new Error(
        `Devspace requires tmux ${MINIMUM_TMUX_VERSION.major}.${MINIMUM_TMUX_VERSION.minor} or newer`,
      );
    }

    if (existsSync(this.socketPath)) {
      const serverVersionResult = await this.runCommand(
        this.requireBinaryPath(),
        ["-S", this.socketPath, "-f", this.configPath, "display-message", "-p", "#{version}"],
        cleanTmuxEnvironment(this.env),
      );

      if (serverVersionResult.exitCode === 0) {
        const serverVersion = parseTmuxVersion(serverVersionResult.stdout);
        if (!serverVersion || !versionsMatch(version, serverVersion)) {
          throw new Error(
            `The running Devspace tmux server uses ${serverVersionResult.stdout.trim() || "an unknown version"}, but this app bundles ${version.major}.${version.minor}. Its sessions were left untouched; reopen them with the matching Devspace version.`,
          );
        }
        await this.applyRuntimeOptions();
      } else if (!reportsNoRunningServer(serverVersionResult)) {
        throw new Error(
          `Unable to verify the running Devspace tmux server without risking its sessions: ${serverVersionResult.stderr.trim() || "unknown tmux error"}`,
        );
      }
    }
    this.versionChecked = true;
  }

  /**
   * Re-apply the options a running server would otherwise keep from whenever it
   * was started. Purely cosmetic, so a failure here is logged and swallowed —
   * refusing to attach to a live session because its title format could not be
   * refreshed would trade a wrong tab name for a lost dev server.
   */
  private async applyRuntimeOptions(): Promise<void> {
    for (const [option, value] of MANAGED_TMUX_RUNTIME_OPTIONS) {
      const result = await this.run(["set-option", "-g", option, value]);
      if (result.exitCode !== 0) {
        console.warn(
          `[managed-tmux] could not refresh ${option} on the running server:`,
          result.stderr.trim() || `exit ${result.exitCode}`,
        );
      }
    }
  }

  private requireBinaryPath(): string {
    const binaryPath = this.getBinaryPath();
    if (binaryPath) return binaryPath;
    throw new Error(
      this.options.isPackaged
        ? "The Devspace managed tmux binary is missing from the application bundle"
        : "Managed terminals require tmux 3.2 or newer; install tmux or set DEVSPACE_TMUX_PATH",
    );
  }

  private run(args: string[], envVars?: Record<string, string>): Promise<TmuxCommandResult> {
    return this.runCommand(
      this.requireBinaryPath(),
      ["-S", this.socketPath, "-f", this.configPath, ...args],
      cleanTmuxEnvironment(this.env, envVars),
    );
  }
}

export function buildExternalTmuxAttachCommand(options: {
  binaryPath: string;
  sessionName: string;
  socketPath?: string;
}): string {
  if (
    options.sessionName.length === 0 ||
    options.sessionName.length > 256 ||
    options.sessionName.includes("\0") ||
    options.sessionName.includes("\r") ||
    options.sessionName.includes("\n")
  ) {
    throw new Error("Invalid external tmux session name");
  }
  if (
    options.socketPath?.includes("\0") ||
    options.socketPath?.includes("\r") ||
    options.socketPath?.includes("\n")
  ) {
    throw new Error("Invalid external tmux socket path");
  }

  const args = [
    "/usr/bin/env",
    "-u",
    "TMUX",
    "-u",
    "TMUX_PANE",
    "TERM=xterm-256color",
    options.binaryPath,
  ];
  if (options.socketPath) args.push("-S", options.socketPath);
  args.push("attach-session", "-t", options.sessionName);
  return args.map(quoteCommandArgument).join(" ");
}
